name: Test Bug Fixes

on:
    pull_request:
        branches: ["main", "master"]

jobs:
    test-project:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: install dependencies
              run: python -m pip install -r requirements.txt
            - name: run tests
              run: python run_all_tests.py | tail -n 1
              continue-on-error: true
